---
# Kernel Samepage Merging (KSM) configuration
disable_ksmtuned: false # Disable Kernel Samepage Merging tuning.
KSM_THRES_COEF: 20 # Percentage of free memory to trigger KSM (default: 20).
KSM_THRES_CONST: 2048 # Free memory threshold in MB to trigger KSM (default: 2048).
KSM_MONITOR_INTERVAL: 60 # Time interval (seconds) between scans (default: 60).
KSM_SLEEP_MSEC: 100 # Pause duration (milliseconds) between scans of 16GB blocks (default: 100).
KSM_NPAGES_MIN: 64 # Minimum number of pages to scan (default: 64).
KSM_NPAGES_MAX: 1250 # Maximum number of pages to scan (default: 1250).
KSM_NPAGES_BOOST: 300 # Pages to boost when free memory is below threshold (default: 300).
KSM_NPAGES_DECAY: -50 # Pages to reduce when free memory exceeds threshold (default: -50).
