---
# Configuration for PXE log node
# This file contains host-specific variables for PXE log node.
# It is used to configure the network settings for the PXE boot process.

configure_network: false # Enable or disable network configuration.

# Configure network interfaces
network_config: |
  auto lo
  iface lo inet loopback

  iface eno1 inet manual

  auto vmbr0
  iface vmbr0 inet static
          address {{ pxelog_ip }}/24
          gateway {{ net_gateway }}
          bridge-ports eno1
          bridge-stp off
          bridge-fd 0

  iface wlp1s0 inet manual

# Set DNS servers
dns_servers: "{{ net_dns }}"

# Set hostname
set_hostname: pxelog # Hostname for the PXE log node.
set_hostname_fqdn: "pxelog.{{ pve_domain_name }}" # Fully Qualified Domain Name (FQDN).

zfs_enabled: false # Enable or disable ZFS configuration.

# Template configuration
templates:
  - name: "ubuntu-24.04"
    description: "Ubuntu 24.04 template for mail node"     # Description of the template.
    id_number: 9110                                        # Unique identifier for the template.
    machine_type: "q35"                                    # Machine type for the template.
    os_type: "l26"                                         # Operating system type.
    bios: "ovmf"                                           # BIOS type for the template.
    disk_size: "1g"                                        # Size of the disk for the template.
    memory: 1024                                           # Memory allocation for the template.
    vcpus: 1                                               # Number of virtual CPUs for the template.
    net_bridge: "vmbr0"                                    # Network interface for the template.
    net_type: "virtio"                                     # Network type for the template.
    scsihw: "virtio-scsi-pci"                              # SCSI hardware type for the template.
    storage: "local-lvm"                                   # Storage for the template.
    iso_image: "noble-server-cloudimg-amd64.img"           # ISO image for the template.
    vendor_file: "vendor-data.yaml"                        # Cloud-init vendor file for the template.
