- name: Secure cluster nodes
  hosts: proxmox
  roles:
    - ssh_server

- name: Create master cluster node
  hosts: proxmox_master
  roles:
    - proxmox_master

- name: Add cluster nodes
  hosts: proxmox
  roles:
    - proxmox_server

- name: Install ceph dependencies
  hosts: ceph
  roles:
    - ceph_node

- name: Create ceph cluster
  hosts: ceph_master
  roles:
    - ceph_master

- name: Create ceph monitors
  hosts: ceph_mon
  roles:
    - ceph_mon

- name: Create ceph managers
  hosts: ceph_mgr
  roles:
    - ceph_mgr

- name: Create ceph OSDs
  hosts: ceph_osd
  roles:
    - ceph_osd

- name: Create ceph pool
  hosts: ceph_master
  roles:
    - ceph_pool

- name: Create ceph metadata service (MDS)
  hosts: ceph_mds
  roles:
    - ceph_mds

- name: Create CephFS
  hosts: ceph_master
  roles:
    - ceph_fs

- name: Create KVM templates
  hosts: proxmox_master
  roles:
    - kvm_templates

- name: Create KVM Core Virtual Machines
  hosts: proxmox_master
  roles:
    - kvm_core_vms

