---
# Networking configuration for PXE node 3
# This file contains host-specific variables for PXE node 3.
# It is used to configure the network settings for the PXE boot process.

configure_network: true # Enable or disable network configuration.

# Configure network interfaces
network_config: |
  auto lo
  iface lo inet loopback

  iface eno1 inet manual

  auto vmbr0
  iface vmbr0 inet dhcp
          # Use DHCP for vmbr0 to automatically obtain an IP address
          address 10.0.2.103/24
          gateway 10.0.2.1
          bridge-ports eno1
          bridge-stp off
          bridge-fd 0

  iface enx00e04c7344e3 inet manual

  auto vmbr1
  iface vmbr1 inet static
          address 10.10.0.103/24
          bridge-ports enx00e04c7344e3
          bridge-stp off
          bridge-fd 0

# Set DNS servers
dns_servers: []

# Set hostname
set_hostname: pxenode3 # Hostname for the PXE node.
set_hostname_fqdn: pxenode3.dmz.homelab.local # Fully Qualified Domain Name (FQDN).

# Configure Ceph OSDs
pve_ceph_osd_device: /dev/nvme0n1 # Device for the Ceph OSD.
# Configure Ceph network interface
pve_ceph_nic: enx00e04c7344e3 # Network interface for Ceph communication.
pve_ceph_nic_ip: 10.10.0.103

# ZFS configuration
zfs_enabled: false # Enable or disable ZFS configuration.
zfs_pool_device: /dev/sda # Device for the ZFS pool.

# Template configuration
templates:
  - name: "ubuntu-24.04"
    description: "Ubuntu 24.04 template for node 3"        # Description of the template.
    id_number: 9003                                        # Unique identifier for the template.
    machine_type: "q35"                                    # Machine type for the template.
    os_type: "l26"                                         # Operating system type.
    bios: "ovmf"                                           # BIOS type for the template.
    disk_size: "1g"                                        # Size of the disk for the template.
    memory: 1024                                           # Memory allocation for the template.
    vcpus: 1                                               # Number of virtual CPUs for the template.
    net_bridge: "vmbr0"                                    # Network interface for the template.
    net_type: "virtio"                                     # Network type for the template.
    scsihw: "virtio-scsi-pci"                              # SCSI hardware type for the template.
    storage: "local-lvm"                                   # Storage for the template.
    iso_image: "noble-server-cloudimg-amd64.img"           # ISO image for the template.
    vendor_file: "vendor-data.yaml"                        # Cloud-init vendor file for the template.
