---
- name: Configure Proxmox ACLs
  proxmox_acl:
    path: "{{ item.path }}"
    roles: "{{ item.roles }}"
    state: "{{ item.state | default('present') }}"
    groups: "{{ item.groups | default([]) }}"
    users: "{{ item.users | default([]) }}"
  with_items: "{{ pve_acls }}"
  no_log: true
  when:
    - not pve_cluster_enabled | bool or (pve_cluster_enabled | bool and inventory_hostname == _init_node)
