---
# Configuration for PXE search node
# This file contains host-specific variables for PXE search node.

configure_network: true # Enable or disable network configuration.

# Set the primary network interface for PXE search node.
pve_primary_nic: enp0s25

# Ceph configuration
pve_ceph_enabled: false # Enable or disable Ceph configuration.
pve_ceph_nic: "" # Network interface for Ceph communication.
pve_ceph_nic_ip: ""
pve_ceph_device_id: ""

# Configure network interfaces
network_config: |
  auto lo
  iface lo inet loopback

  iface {{ pve_primary_nic }} inet manual

  auto vmbr0
  iface vmbr0 inet static
          address {{ pxesearch_ip }}/24
          gateway {{ net_gateway }}
          bridge-ports {{ pve_primary_nic }}
          bridge-stp off
          bridge-fd 0

  iface wlp2s0 inet manual

# Set DNS servers
dns_servers: "{{ net_dns }}"

# Set hostname
set_hostname: pxesearch # Hostname for the PXE node.
set_hostname_fqdn: "pxesearch.{{ pve_domain_name }}" # Fully Qualified Domain Name (FQDN).

# ZFS configuration
pve_zfs_enabled: true # Enable or disable ZFS configuration.
pve_zfs_device_id: nvme-SAMSUNG_MZVLW256HEHP-000L7_S35ENX0J402919

# Template configuration
templates:
  - name: "ubuntu-24.04"
    description: "Ubuntu 24.04 template for search node"   # Description of the template.
    id_number: 9120                                        # Unique identifier for the template.
    machine_type: "q35"                                    # Machine type for the template.
    os_type: "l26"                                         # Operating system type.
    bios: "ovmf"                                           # BIOS type for the template.
    disk_size: "1g"                                        # Size of the disk for the template.
    memory: 1024                                           # Memory allocation for the template.
    vcpus: 1                                               # Number of virtual CPUs for the template.
    net_bridge: "vmbr0"                                    # Network interface for the template.
    net_type: "virtio"                                     # Network type for the template.
    scsihw: "virtio-scsi-pci"                              # SCSI hardware type for the template.
    storage: "local-lvm"                                   # Storage for the template.
    iso_image: "noble-server-cloudimg-amd64.img"           # ISO image for the template.
    vendor_file: "vendor-data.yaml"                        # Cloud-init vendor file for the template.
