---
- name: Copy cloud-init file to PXE node
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/lib/vz/snippets/{{ item | basename }}"
  with_items:
    - vendor-data.yaml

- name: Copy file to create templates for PXE node
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/{{ item | basename }}"
  with_items:
    - create_templates.sh

- name: Ensure create_templates.sh is executable
  ansible.builtin.file:
    path: "~/create_templates.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 'a+x'

- name: Create argument
  ansible.builtin.set_fact:
    templates_args: "-i '{{ id_number }}' -n '{{ name }}' -machine '{{ machine_type }}' -os '{{ os_type }}' -b '{{ bios }}' -resize '{{ disk_size }}' -m {{ memory }} -net-bridge '{{ net_bridge }}' -net-type '{{ net_type }}' -scsihw '{{ scsihw }}' -s '{{ storage }}' -img '{{ iso_path }}/{{ iso_image }}' -vendor-file '{{ vendor_file }}'"

- name: Create templates for PXE node
  ansible.builtin.command: "bash ~/create_templates.sh {{ templates_args }}"
  args:
    chdir: "/home/{{ ansible_user }}"
