---
# roles/proxmox_prepare/tasks/main.yaml
# Prepare the Proxmox hosts

- name: Ensure python3-pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: yes

- name: Install Proxmoxer Python module
  ansible.builtin.pip:
    name: proxmoxer
    state: present
    executable: pip3
  become: yes
