- name: Install ceph packages
  shell: yes | pveceph install
  args:
    creates: /etc/apt/sources.list.d/ceph.list

- name: Configure ceph network
  blockinfile:
    path: /etc/network/interfaces
    block: |

      auto {{ ceph_nic }}

      iface {{ ceph_nic }} inet static
          address {{ ceph_ip }}
          netmask 255.255.255.0

  notify: restart networking

