- name: Download Ubuntu 24.04 cloud image
  ansible.builtin.get_url:
    url: "{{ ubuntu_cloud_image_url }}"
    dest: "{{ ubuntu_cloud_image }}"

- name: Check for ubuntu_m1_nano template type
  ansible.builtin.command: "qm config {{ ubuntu_m1_nano_template_id }}"
  register: ubuntu_m1_nano_template_status
  ignore_errors: true
  changed_when: false

- name: Create ubuntu_m1_nano template (1 core 512MB RAM)
  when: ubuntu_m1_nano_template_status.rc > 0
  ansible.builtin.command: "qm create {{ ubuntu_m1_nano_template_id }} -name ubuntu-noble.m1-nano -memory 512 -net0 virtio,bridge=vmbr0 -cores 1 -sockets 1 -ostype l26 -ide2 ceph-vm:cloudinit -scsihw virtio-scsi-pci -boot c -serial0 socket"

- name: Import ubuntu_m1_nano disk image
  when: ubuntu_m1_nano_template_status.rc > 0
  ansible.builtin.command: "qm importdisk {{ ubuntu_m1_nano_template_id }} {{ ubuntu_cloud_image }} ceph-vm"

- name: Attach ubuntu_m1_nano disk
  when: ubuntu_m1_nano_template_status.rc > 0
  ansible.builtin.command: "qm set {{ ubuntu_m1_nano_template_id }} -scsihw virtio-scsi-pci -scsi0 ceph-vm:vm-{{ ubuntu_m1_nano_template_id }}-disk-0"

- name: Create ubuntu_m1_nano boot settings
  when: ubuntu_m1_nano_template_status.rc > 0
  ansible.builtin.command: "qm set {{ ubuntu_m1_nano_template_id }} -ide2 ceph-vm:cloudinit -boot c -bootdisk scsi0"

- name: Convert ubuntu_m1_nano to template
  when: ubuntu_m1_nano_template_status.rc > 0
  ansible.builtin.command: "qm template {{ ubuntu_m1_nano_template_id }}"
