---
- name: Copy cloud-init file to PXE node
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/lib/vz/snippets/{{ item | basename }}"
  with_items:
    - vendor-data.yaml

- name: Copy file to create templates for PXE node
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/{{ item | basename }}"
  with_items:
    - build-template.sh

- name: Ensure build-template.sh is executable
  ansible.builtin.file:
    path: "~/build-template.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 'a+x'

- name: Create templates for PXE node
  ansible.builtin.include_tasks: create_templates.yml
  loop: "{{ templates }}"
  loop_control:
    loop_var: template
  when: templates is defined and templates | length > 0
