---
# Configuration for PXE mail node
# This file contains host-specific variables for PXE mail node.

configure_network: true # Enable or disable network configuration.

# Set the primary network interface for PXE log node.
pve_primary_nic: eno1

# Ceph configuration
pve_ceph_enabled: false # Enable or disable Ceph configuration.
pve_ceph_nic: "" # Network interface for Ceph communication.
pve_ceph_nic_ip: ""
pve_ceph_device_id: ""

# Configure network interfaces
network_config: |
  auto lo
  iface lo inet loopback

  iface {{ pve_primary_nic }} inet manual

  auto vmbr0
  iface vmbr0 inet static
          address {{ pxemail_ip }}/24
          gateway {{ net_gateway }}
          bridge-ports {{ pve_primary_nic }}
          bridge-stp off
          bridge-fd 0

  iface wlp0s20f3 inet manual

# Set DNS servers
dns_servers: "{{ net_dns }}"

# Set hostname
set_hostname: pxemail # Hostname for the PXE node.
set_hostname_fqdn: "pxemail.{{ pve_domain_name }}" # Fully Qualified Domain Name (FQDN).

# ZFS configuration
pve_zfs_create_pools: false # Enable or disable ZFS configuration.
pve_zfs_pools: []

# Template configuration
templates:
  - name: "ubuntu-22.04"
    description: "Ubuntu 22.04 template for mail node"     # Description of the template.
    id_number: 9101                                        # Unique identifier for the template.
    machine_type: "q35"                                    # Machine type for the template.
    os_type: "l26"                                         # Operating system type.
    bios: "ovmf"                                           # BIOS type for the template.
    disk_size: "1g"                                        # Size of the disk for the template.
    memory: 1024                                           # Memory allocation for the template.
    vcpus: 1                                               # Number of virtual CPUs for the template.
    net_bridge: "vmbr0"                                    # Network interface for the template.
    net_type: "virtio"                                     # Network type for the template.
    scsihw: "virtio-scsi-pci"                              # SCSI hardware type for the template.
    storage: "local-lvm"                                   # Storage for the template.
    iso_image: "jammy-server-cloudimg-amd64.img"           # ISO image for the template.
    vendor_file: "vendor-data.yaml"                        # Cloud-init vendor file for the template.
  - name: "ubuntu-24.04"
    description: "Ubuntu 24.04 template for mail node"     # Description of the template.
    id_number: 9102                                        # Unique identifier for the template.
    machine_type: "q35"                                    # Machine type for the template.
    os_type: "l26"                                         # Operating system type.
    bios: "ovmf"                                           # BIOS type for the template.
    disk_size: "1g"                                        # Size of the disk for the template.
    memory: 1024                                           # Memory allocation for the template.
    vcpus: 1                                               # Number of virtual CPUs for the template.
    net_bridge: "vmbr0"                                    # Network interface for the template.
    net_type: "virtio"                                     # Network type for the template.
    scsihw: "virtio-scsi-pci"                              # SCSI hardware type for the template.
    storage: "local-lvm"                                   # Storage for the template.
    iso_image: "noble-server-cloudimg-amd64.img"           # ISO image for the template.
    vendor_file: "vendor-data.yaml"                        # Cloud-init vendor file for the template.
