---
- name: Import realm configuration
  ansible.builtin.import_tasks: realms_config.yml
  when:
    - not pve_cluster_enabled | bool or (pve_cluster_enabled and inventory_hostname == groups[pve_group][0])
    - pve_domains_cfg | length > 0

- name: Select ldap-based realms with sync
  ansible.builtin.set_fact:
    pve_ldap_realms_with_sync: |
      {{ pve_domains_cfg | selectattr('type', 'in', ['ad', 'ldap'])
                         | selectattr('sync', 'defined') }}

- name: Sync ldap-based realms
  ansible.builtin.include_tasks: realms_sync.yml
  loop: "{{ pve_ldap_realms_with_sync | flatten(levels=1) }}"
  loop_control:
    loop_var: pve_ldap_realm
  when:
    - not pve_cluster_enabled | bool or (pve_cluster_enabled and inventory_hostname == groups[pve_group][0])
    - pve_domains_cfg | length > 0
    - pve_ldap_realm.sync | bool
