---
# Kernel Management
install_specific_kernel: false # Enable installation of a specific kernel version.
specific_kernel_version: "6.11.0-2-pve-signed" # The specific kernel version to install.
pin_kernel_enabled: false # Enable pinning a specific kernel version.
pin_kernel_version: "6.8.12-4-pve" # The kernel version to pin.
unpin_kernel_enabled: false # Enable unpinning a previously pinned kernel version.
unpin_kernel_version: "6.8.12-4-pve" # The kernel version to unpin.
clean_old_kernels: false
kernels_to_keep: 2
