---
# The name of ssh daemon
sshd: ssh

# Where is ssh config is located at
sshd_config: /etc/ssh/sshd_config

disable_root_login: false
disable_password_auth: false
change_default_ssh_port: false
new_ssh_port: 22
