---
- name: Configure APT repositories
  block:
    - name: Get Proxmox version
      ansible.builtin.command: pveversion
      register: proxmox_pveversion_info
      changed_when: false

    - name: Extract Proxmox major version
      ansible.builtin.set_fact:
        proxmox_pve_major: "{{ proxmox_pveversion_info.stdout.split('/')[1].split('.')[0] | int }}"

    - name: Gather distribution specific variables
      ansible.builtin.include_vars: "debian-{{ ansible_distribution_release }}.yml"

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Ensure gpg is installed
      ansible.builtin.apt:
        name: gpg
        state: present

    - name: Trust Proxmox' packaging key on Debian < 12
      ansible.builtin.apt_key:
        data: "{{ lookup('file', pve_release_key) }}"
        id: "{{ pve_release_key_id }}"
        state: present
      when: "ansible_distribution_major_version | int < 12"

    - name: Copy apt configuration file for Debian
      ansible.builtin.template:
        src: sources.list.j2
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: '0644'
        force: true
      register: _apt_debian_config_result
      notify: Update apt cache

    - name: Copy apt configuration file for Proxmox
      ansible.builtin.template:
        src: proxmox.list.j2
        dest: /etc/apt/sources.list.d/proxmox.list
        owner: root
        group: root
        mode: '0644'
        force: true
      register: _apt_config_result
      notify: Update apt cache

    - name: Copy apt configuration file for Proxmox Ceph
      ansible.builtin.template:
        src: ceph.list.j2
        dest: /etc/apt/sources.list.d/ceph.list
        owner: root
        group: root
        mode: '0644'
        force: true
      register: _apt_ceph_config_result
      notify: Update apt cache

    - name: Copy apt configuration file for Proxmox Enterprise
      ansible.builtin.template:
        src: pve-enterprise.list.j2
        dest: /etc/apt/sources.list.d/pve-enterprise.list
        owner: root
        group: root
        mode: '0644'
        force: true
      register: _apt_enterprise_config_result
      notify: Update apt cache

- name: Run apt-get dist-upgrade on repository changes
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 0
    upgrade: dist
  when: _apt_config_result.changed or _apt_ceph_config_result.changed or _apt_enterprise_config_result.changed or _apt_debian_config_result.changed
  changed_when: _dist_upgrade is succeeded
  retries: 3
  register: _dist_upgrade
  until: _dist_upgrade is succeeded
