---
- name: Configure Proxmox groups
  proxmox_group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    comment: "{{ item.comment | default(omit) }}"
  with_items: "{{ pve_groups }}"
  no_log: "{{ pve_no_log }}"
  when:
    - not pve_cluster_enabled | bool or (pve_cluster_enabled | bool and inventory_hostname == _init_node)
