---
- name: Configure Proxmox user accounts
  proxmox_user:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    enable: "{{ item.enable | default(omit) }}"
    groups: "{{ item.groups | default([]) }}"
    comment: "{{ item.comment | default(omit) }}"
    email: "{{ item.email | default(omit) }}"
    firstname: "{{ item.firstname | default(omit) }}"
    lastname: "{{ item.lastname | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    expire: "{{ item.expire | default(omit) }}"
  with_items: "{{ pve_users }}"
  no_log: "{{ pve_no_log }}"
  when:
    - not pve_cluster_enabled | bool or (pve_cluster_enabled | bool and inventory_hostname == _init_node)
