---
zfs_pool_name: "zfspool"
zfs_device_id: "{{ pve_zfs_device_id }}"
set_zfs_arc: true  # Enable ZFS ARC configuration.
zfs_arc_min: 1
zfs_arc_max: 8
zfs_arc_min_bytes: "{{ zfs_arc_min * 1024 * 1024 * 1024 - 1 }}"
zfs_arc_max_bytes: "{{ zfs_arc_max * 1024 * 1024 * 1024 }}"
